version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      
  pre_build:
    commands:
      - docker-compose up -d
  build:
    commands:
      - apt-get update -y
      - apt-get install -y maven
      - mvn install
      - mvn test
reports:
  Selenium:
    file-format: CucumberJson
    files:
      - target/json/output.json
