version: 0.2

phases:
  pre_build:
    commands:
      - sudo docker-compose up
  build:
    commands:
      - mvn test
reports:
  Selenium:
    file-format: CucumberJson
    files:
      - target/json/output.json
